# Introduction to Data Science 2025

# Week 1

## Exercise 1 | Matrix warm-up
*Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ffcccdff"> A</span> and <span style="background-color: #ffccd5ff"> B</span> which each have the integers <span style="background-color: #de144dff"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [30]:
import pandas as pd
import numpy as np
import sklearn.datasets
import nltk

In [31]:
A = list(range(0,(1*10**7)))
B = list(range(0,(1*10**7)))


2. Create a function that uses a <span style="background-color: #ffccccff"> for loop</span> or equivalent to return a new array <span style="background-color: #ffccccff"> C</span>, which contains the <span style="background-color: #ffccccff"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ffccccff"> 0, 2, 4, etc</span>.

In [32]:
def add_with_for(A,B):
    C = []
    for num in range(len(A)):
        C.append(A[num]+B[num])

    return C

3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #f31221ff"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [33]:
D = np.array(range(0,(1*10**7)))
E = np.array(range(0,(1*10**7)))

def add_with_numpy(A,B):
    C = A+B
    return C




### 1.2 Array manipulation

<span style="background-color: #de1717ff"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #f80c0cff"> np.reshape</span>]*

In [34]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
A = np.array(range(0,100)).reshape(10,10)
A

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

2. Create the following array:

In [36]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [37]:
A = np.tile(np.array((0.,1.)),(10,5))
A

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

3. Create the following array (D):

In [38]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [39]:
D = np.full((10,10), 1.)
np.fill_diagonal(D,0.)
D

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

4. Create the following array (E):

In [40]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
E = np.full((10,10), 1.)
np.fill_diagonal(np.fliplr(E),0.)
E

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

5. Call the last two matrices <span style="background-color: #ffccccff">D</span> and <span style="background-colorrgba(255, 204, 207, 1)f2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ffcccfff">det(DE)</span> and <span style="background-color: #ffccccff">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [42]:
# Use this cell for your code

DE = np.linalg.det(np.dot(D,E))

D_plus_E = np.dot(np.linalg.det(D),np.linalg.det(E))

print(DE, D_plus_E)
print(np.isclose(DE,D_plus_E))

-81.00000000000003 -81.0
True


-- *Use this markdown cell for your written answer* --

DET(AB) = DET(A)DET(B) is proved in many linear algebra books. The theorom follows that if A is not invertable then AB is not invertable and 0 = DET(AB)= DET(A)DET(B)=0 and if A is invertible there exists a row wise operation which satisfies DET(AB)=DET(A)DET(B)

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ee282fff">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #f70d0dff">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [43]:
housing_data = sklearn.datasets.fetch_california_housing(as_frame=True).frame




2. Select rows where the average number of bedrooms <span style="background-color: #df0d34ff">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ee1616ff">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #da0e1fff">np.where</span>]*

In [44]:
len(housing_data[housing_data['AveBedrms']>2])

235

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #e9080fff">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [45]:
housing_data[(housing_data['HouseAge']>=1) & (housing_data['HouseAge']<=3)]

MedInc  HouseAge   AveRooms  AveBedrms  Population  AveOccup  Latitude  \
59     2.5625       2.0   2.771930   0.754386        94.0  1.649123     37.82   
854    2.8750       2.0   5.624161   1.979866       240.0  1.610738     37.59   
871    6.0824       3.0   5.090447   1.039230      7205.0  2.617145     37.52   
959    4.4087       3.0   5.385965   1.276316       793.0  1.739035     37.70   
976    2.1187       3.0   3.394794   1.006508       769.0  1.668113     37.66   
...       ...       ...        ...        ...         ...       ...       ...   
19536  4.2500       1.0  20.125000   2.928571       402.0  3.589286     37.65   
19561  4.6484       2.0   6.406607   1.059720      2784.0  3.537484     37.59   
19650  2.6103       2.0   7.308594   1.597656       707.0  2.761719     37.52   
20070  2.4191       3.0   6.274194   1.645161       422.0  2.268817     37.99   
20367  8.0428       3.0   8.239437   1.042254       493.0  3.471831     34.16   

       Longitude  MedHouseVal  
59       -122.29      0.60000  
854      -122.01      2.37500  
871      -122.07      2.73500  
959      -121.93      2.25600  
976      -121.89      2.31300  
...          ...          ...  
19536    -120.93      1.89200  
19561    -120.98      1.45900  
19650    -120.88      1.33600  
20070    -120.35      2.17500  
20367    -118.94      5.00001  

[124 rows x 9 columns]

4. Find the mean of the block group population <span style="background-color: #e40c0cff">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [46]:
housing_data[housing_data['MedHouseVal']>0.25]['Population'].mean()

1425.6833737275813

## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #f70b0bff">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ec081eff">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [47]:
automotive = pd.read_json('Automotive_5.json', lines=True)

In [48]:
automotive

overall  verified   reviewTime      reviewerID        asin  \
0              4     False   05 1, 2015   A8WEXFRWX1ZHH  0209688726   
1              1      True  04 19, 2018   ABCA1A8E4DGV1  0209688726   
2              1      True  04 16, 2018  A1NX8HM89FRQ32  0209688726   
3              3      True  04 13, 2018  A1X77G023NY0KY  0209688726   
4              5      True   04 8, 2018  A3GK37JO2MGW6Q  0209688726   
...          ...       ...          ...             ...         ...   
1711514        5      True  06 19, 2018  A3H86E5N0F1Q5R  B01HJFDJ8S   
1711515        4      True  08 23, 2017   AXH645B4SSAJY  B01HJFDJ8S   
1711516        5      True   08 8, 2017    AMGJLCCNVFB8  B01HJFDJ8S   
1711517        5      True  08 24, 2018  A1MJUNTX7CTR5U  B01HJI17Y8   
1711518        5      True  06 26, 2018   AF67UV2T2TFWB  B01HJI17Y8   

                        style reviewerName  \
0           {'Color:': ' AC'}   Goldengate   
1         {'Color:': ' Blue'}          noe   
2        {'Color:': ' Black'}       Eduard   
3           {'Color:': ' CA'}       Lauren   
4        {'Color:': ' Black'}        danny   
...                       ...          ...   
1711514                   NaN      John Jr   
1711515                   NaN       Brian.   
1711516                   NaN      John M.   
1711517  {'Size:': ' H8-NEW'}         JKPA   
1711518  {'Size:': ' H8-NEW'}      DDraper   

                                                reviewText  \
0        After I wrote the below review, the manufactur...   
1        It sucks barely picks up anything definitely n...   
2        Well to write a short one, it blew 2 fuses of ...   
3        I have absolutely no memory of buying this but...   
4                                     it ok it does it job   
...                                                    ...   
1711514                        Fast Shipping, Works Great!   
1711515  Fit isn't great, relays are very hard to press...   
1711516  I bought an auxiliary horn for my car and it n...   
1711517  Way better than stock. Nice bright and white. ...   
1711518  Great product fast shipping and awesome commun...   

                                                   summary  unixReviewTime  \
0        Works well if you place phone in horizontally ...      1430438400   
1                                                    sucks      1524096000   
2                                                Defective      1523836800   
3                               Looks cool! Probably works      1523577600   
4                                               Five Stars      1523145600   
...                                                    ...             ...   
1711514                                       Works Great!      1529366400   
1711515                                         Four Stars      1503446400   
1711516   I bought an auxiliary horn for my car and it ...      1502150400   
1711517                             NICE, BRIGHT AND WHITE      1535068800   
1711518                                         Five Stars      1529971200   

        vote                                              image  
0        NaN                                                NaN  
1        NaN                                                NaN  
2        NaN                                                NaN  
3        NaN                                                NaN  
4        NaN                                                NaN  
...      ...                                                ...  
1711514  NaN                                                NaN  
1711515  NaN                                                NaN  
1711516  NaN                                                NaN  
1711517  NaN  [https://images-na.ssl-images-amazon.com/image...  
1711518  NaN                                                NaN  

[1711519 rows x 12 columns]

2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ef0303ff">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #e90a24ff">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [49]:
automotive['reviewText']=automotive['reviewText'].str.lower()

automotive

#Not sure if this is computationally the fastest

overall  verified   reviewTime      reviewerID        asin  \
0              4     False   05 1, 2015   A8WEXFRWX1ZHH  0209688726   
1              1      True  04 19, 2018   ABCA1A8E4DGV1  0209688726   
2              1      True  04 16, 2018  A1NX8HM89FRQ32  0209688726   
3              3      True  04 13, 2018  A1X77G023NY0KY  0209688726   
4              5      True   04 8, 2018  A3GK37JO2MGW6Q  0209688726   
...          ...       ...          ...             ...         ...   
1711514        5      True  06 19, 2018  A3H86E5N0F1Q5R  B01HJFDJ8S   
1711515        4      True  08 23, 2017   AXH645B4SSAJY  B01HJFDJ8S   
1711516        5      True   08 8, 2017    AMGJLCCNVFB8  B01HJFDJ8S   
1711517        5      True  08 24, 2018  A1MJUNTX7CTR5U  B01HJI17Y8   
1711518        5      True  06 26, 2018   AF67UV2T2TFWB  B01HJI17Y8   

                        style reviewerName  \
0           {'Color:': ' AC'}   Goldengate   
1         {'Color:': ' Blue'}          noe   
2        {'Color:': ' Black'}       Eduard   
3           {'Color:': ' CA'}       Lauren   
4        {'Color:': ' Black'}        danny   
...                       ...          ...   
1711514                   NaN      John Jr   
1711515                   NaN       Brian.   
1711516                   NaN      John M.   
1711517  {'Size:': ' H8-NEW'}         JKPA   
1711518  {'Size:': ' H8-NEW'}      DDraper   

                                                reviewText  \
0        after i wrote the below review, the manufactur...   
1        it sucks barely picks up anything definitely n...   
2        well to write a short one, it blew 2 fuses of ...   
3        i have absolutely no memory of buying this but...   
4                                     it ok it does it job   
...                                                    ...   
1711514                        fast shipping, works great!   
1711515  fit isn't great, relays are very hard to press...   
1711516  i bought an auxiliary horn for my car and it n...   
1711517  way better than stock. nice bright and white. ...   
1711518  great product fast shipping and awesome commun...   

                                                   summary  unixReviewTime  \
0        Works well if you place phone in horizontally ...      1430438400   
1                                                    sucks      1524096000   
2                                                Defective      1523836800   
3                               Looks cool! Probably works      1523577600   
4                                               Five Stars      1523145600   
...                                                    ...             ...   
1711514                                       Works Great!      1529366400   
1711515                                         Four Stars      1503446400   
1711516   I bought an auxiliary horn for my car and it ...      1502150400   
1711517                             NICE, BRIGHT AND WHITE      1535068800   
1711518                                         Five Stars      1529971200   

        vote                                              image  
0        NaN                                                NaN  
1        NaN                                                NaN  
2        NaN                                                NaN  
3        NaN                                                NaN  
4        NaN                                                NaN  
...      ...                                                ...  
1711514  NaN                                                NaN  
1711515  NaN                                                NaN  
1711516  NaN                                                NaN  
1711517  NaN  [https://images-na.ssl-images-amazon.com/image...  
1711518  NaN                                                NaN  

[1711519 rows x 12 columns]

3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #f90d19ff">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [55]:
import string
stop_words = set(open("stopwords-en.txt").read().split('\n'))

def sentence_parser(sentence):
    sentence = str(sentence)
    r_sentence = []
    sentence = sentence.translate(str.maketrans('', '', string.punctuation))
    for x in sentence.split():
        if x not in stop_words:
            r_sentence.append(x)
    result = ' '.join(r_sentence)
    return result

# Again not sure if this is the fastest


for row in range(len(automotive)):
    automotive.loc[row, 'reviewText'] = sentence_parser(automotive.loc[row, 'reviewText'])


# Well this isin't matching to the one above but the stop word list doesn't contain for example the words like use, instead, placed etc so I'm pretty sure this is correct.


4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #f11316ff">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [60]:
# Use this cell for your code
stemmer = nltk.PorterStemmer()

def stem(sentence):
    r_sentence=[]
    for x in sentence.split():
        r_sentence.append(stemmer.stem(x))
    result = ' '.join(r_sentence)
    return result
        

for row in range(len(automotive)):
    automotive.loc[row, 'reviewText'] = stem(automotive.loc[row, 'reviewText'])

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #f6080cff">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #f9162dff">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #f90c1cff">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [65]:
# Use this cell for your code
pos = automotive[automotive['overall']>3]['reviewText']

neq = automotive[automotive['overall']<3]['reviewText']

pos.to_csv('pos.txt')
neq.to_csv('neq.txt')



## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

In [66]:
#1 SELECT firstname, lastname, hiredate FROM Employees WHERE hiredate > '1994-01-01';
#2 SELECT CustomerID ,COUNT(DISTINCT(OrderId)) FROM orders GROUP BY CustomerID;
#3 SELECT CustomerName FROM Invoices WHERE ProductName=='Chai';
#4 SELECT OrderId,OrderDate, ShippedDate From Invoices WHERE ShippedDate ISNULL; I quess this is how you are supposed to track this :D
#5 SELECT CustomerId, Count(OrderId) FROM orders GROUP BY CustomerId ORDER BY Count(OrderId) DESC LIMIT 1; # Not sure if this is the most effective tactic but it was easier the subquerying.



**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**